version: '3.9'

services:
  db:
    container_name: amthauer_db
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - db_amthauer_data:/var/lib/postgresql/data
    ports:
      - "5441:5432"
    env_file:
      - .env

  app:
    container_name: amthauer_api
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/usr/src/app
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    ports:
      - "8078:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_amthauer_data:
