# Generated by Django 4.2.1 on 2023-06-12 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amthauer', '0005_alter_scoreresult_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreresult',
            name='session',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_result', to='amthauer.session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='participant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='amthauer.participant'),
        ),
    ]
