# Generated by Django 4.2.1 on 2023-06-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amthauer', '0006_alter_scoreresult_session_alter_session_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
